// Below is an example of how to use index.js.

// exampleAction Types

export const EXAMPLE_TYPE = 'EXAMPLE_TYPE';

// authAction Types

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SIGN_IN_FETCH = 'SIGN_IN_FETCH';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
export const SIGN_UP_FETCH = 'SIGN_UP_FETCH';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const SIGN_OUT_FETCH = 'SIGN_OUT_FETCH';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAIL = 'SIGN_OUT_FAIL';
export const SIGN_UP_PENDING = 'SIGN_UP_PENDING';
export const CONFIRM_FETCH = 'CONFIRM_FETCH';
export const CONFIRM_FAIL = 'CONFIRM_FAIL';
export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const IS_LOGGED_OUT = 'IS_LOGGED_OUT';
export const TOGGLE_FORGOT_PASSWORD = 'TOGGLE_FORGOT_PASSWORD';
export const FORGOT_PASSWORD_FETCH = 'FORGOT_PASSWORD_FETCH';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const FORGOT_PASSWORD_PENDING = 'FORGOT_PASSWORD_PENDING';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const SEND_REGISTER_ERROR = 'SEND_REGISTER_ERROR';

// userAction Types

export const GET_USERHOUSE_FETCH = 'GET_USERHOUSE_FETCH';
export const GET_USERHOUSE_SUCCESS = 'GET_USERHOUSE_SUCCESS';
export const GET_USERHOUSE_FAIL = 'GET_USERHOUSE_FAIL';
export const MAKE_USER_FETCH = 'MAKE_USER_FETCH';
export const MAKE_USER_SUCCESS = 'MAKE_USER_SUCCESS';
export const MAKE_USER_FAIL = 'MAKE_USER_FAIL';
export const GET_USER_SESSION_FETCH = 'GET_USER_SESSION_FETCH';
export const GET_USER_SESSION_SUCCESS = 'GET_USER_SESSION_SUCCESS';
export const GET_USER_SESSION_FAIL = 'GET_USER_SESSION_FAIL';
export const UPDATE_USER_ATTRIBUTES_FETCH = 'UPDATE_USER_ATTRIBUTES_FETCH';
export const UPDATE_USER_ATTRIBUTES_SUCCESS = 'UPDATE_USER_ATTRIBUTES_SUCCESS';
export const UPDATE_USER_ATTRIBUTES_FAIL = 'UPDATE_USER_ATTRIBUTES_FAIL';
export const UPDATE_USER_FULLNAME_FETCH = 'UPDATE_USER_FULLNAME_FETCH';
export const UPDATE_USER_FULLNAME_SUCCESS = 'UPDATE_USER_FULLNAME_SUCCESS';
export const UPDATE_USER_FULLNAME_FAIL = 'UPDATE_USER_FULLNAME_FAIL';
export const UPDATE_USER_EMAIL_FETCH = 'UPDATE_USER_EMAIL_FETCH';
export const UPDATE_USER_EMAIL_PENDING = 'UPDATE_USER_EMAIL_PENDING';
export const UPDATE_USER_EMAIL_FAIL = 'UPDATE_USER_EMAIL_FAIL';
export const UPDATE_USER_EMAIL_CONFIRM_FETCH = 'UPDATE_USER_EMAIL_CONFIRM_FETCH';
export const UPDATE_USER_EMAIL_SUCCESS = 'UPDATE_USER_EMAIL_SUCCESS';
export const UPDATE_USER_EMAIL_CONFIRM_FAIL = 'UPDATE_USER_EMAIL_CONFIRM_FAIL';
export const UPDATE_USER_EMAIL_CANCEL_FETCH = 'UPDATE_USER_EMAIL_CANCEL_FETCH';
export const UPDATE_USER_EMAIL_CANCEL_SUCCESS = 'UPDATE_USER_EMAIL_CANCEL_SUCCESS';
export const UPDATE_USER_EMAIL_CANCEL_FAIL = 'UPDATE_USER_EMAIL_CANCEL_FAIL';

// houseAction Types

export const MAKE_HOUSE_FETCH = 'MAKE_HOUSE_FETCH';
export const MAKE_HOUSE_SUCCESS = 'MAKE_HOUSE_SUCCESS';
export const MAKE_HOUSE_FAIL = 'MAKE_HOUSE_FAIL';
export const EDIT_HOUSE_INFO = 'EDIT_HOUSE_INFO';
export const SAVE_HOUSE_INFO = 'SAVE_HOUSE_INFO';
export const CANCEL_SAVE_HOUSE_INFO = 'CANCEL_SAVE_HOUSE_INFO';
export const SAVE_HOUSE_INFO_FETCH = 'SAVE_HOUSE_INFO_FETCH';
export const SAVE_HOUSE_INFO_SUCCESS = 'SAVE_HOUSE_INFO_SUCCESS';
export const SAVE_HOUSE_INFO_FAIL = 'SAVE_HOUSE_INFO_FAIL';

// playgroundAction Types

export const SET_CURRENT_COUNTER_TOP = 'SET_CURRENT_COUNTER_TOP';
export const SET_CURRENT_ROOF = 'SET_CURRENT_ROOF';
export const SET_CURRENT_SIDING = 'SET_CURRENT_SIDING';
export const SET_CURRENT_AC = 'SET_CURRENT_AC';
export const SET_CURRENT_FURNACE = 'SET_CURRENT_FURNACE';
export const SET_CURRENT_FLOORING = 'SET_CURRENT_FLOORING';
export const SET_CURRENT_ADDING_SQFT = 'SET_CURRENT_ADDING_SQFT';
export const SET_CURRENT_PAINTING = 'SET_CURRENT_PAINTING';
export const SET_CURRENT_VALUE = 'SET_CURRENT_VALUE';

// landingpageAction Types

export const GET_VALUATION_FETCH = 'GET_VALUATION_FETCH';
export const GET_VALUATION_SUCCESS = 'GET_VALUATION_SUCCESS';
export const GET_VALUATION_FAIL = 'GET_VALUATION_FAIL';

// displayAction Types

export const TOGGLE_SIDEBAR_DRAWER = 'TOGGLE_SIDEBAR_DRAWER';
export const CLOSE_SIDEBAR_DRAWER = 'CLOSE_SIDEBAR_DRAWER';
export const SET_MOBILE_UPGRADE = 'SET_MOBILE_UPGRADE';

// storageAction Types

export const IMAGE_UPLOAD_FETCH = 'IMAGE_UPLOAD_FETCH';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const IMAGE_UPLOAD_FAIL = 'IMAGE_UPLOAD_FAIL';
export const IMAGE_DOWNLOAD_FETCH = 'IMAGE_DOWNLOAD_FETCH';
export const IMAGE_DOWNLOAD_SUCCESS = 'IMAGE_DOWNLOAD_SUCCESS';
export const IMAGE_DOWNLOAD_FAIL = 'IMAGE_DOWNLOAD_FAIL';
export const LIST_GALLERY_FETCH = 'LIST_GALLERY_FETCH';
export const LIST_GALLERY_SUCCESS = 'LIST_GALLERY_SUCCESS';
export const LIST_GALLERY_FAIL = 'LIST_GALLERY_FAIL';
export const GALLERY_UPLOAD_FETCH = 'GALLERY_UPLOAD_FETCH';
export const GALLERY_UPLOAD_SUCCESS = 'GALLERY_UPLOAD_SUCCESS';
export const GALLERY_UPLOAD_FAIL = 'GALLERY_UPLOAD_FAIL';

// designStudio Types

export const GET_DESIGNS_FETCH = 'GET_DESIGNS_FETCH';
export const GET_DESIGNS_SUCCESS = 'GET_DESIGNS_SUCCESS';
export const GET_DESIGNS_FAIL = 'GET_DESIGNS_FAIL';
export const NEXT_PAGE_FETCH = 'NEXT_PAGE_FETCH';
export const NEXT_PAGE_SUCCESS = 'NEXT_PAGE_SUCCESS';
export const NEXT_PAGE_FAIL = 'NEXT_PAGE_FAIL';
