// Below is an example of how to use index.js.

// exampleAction Types

export const EXAMPLE_TYPE = 'EXAMPLE_TYPE';

// authAction Types

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SIGN_IN_FETCH = 'SIGN_IN_FETCH';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
export const SIGN_UP_FETCH = 'SIGN_UP_FETCH';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const SIGN_OUT_FETCH = 'SIGN_OUT_FETCH';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAIL = 'SIGN_OUT_FAIL';
export const SIGN_UP_PENDING = 'SIGN_UP_PENDING';
export const CONFIRM_FETCH = 'CONFIRM_FETCH';
export const CONFIRM_FAIL = 'CONFIRM_FAIL';
export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const IS_LOGGED_OUT = 'IS_LOGGED_OUT';

// userAction Types

export const GET_USERHOUSE_FETCH = 'GET_USERHOUSE_FETCH';
export const GET_USERHOUSE_SUCCESS = 'GET_USERHOUSE_SUCCESS';
export const GET_USERHOUSE_FAIL = 'GET_USERHOUSE_FAIL';
export const MAKE_USER_FETCH = 'MAKE_USER_FETCH';
export const MAKE_USER_SUCCESS = 'MAKE_USER_SUCCESS';
export const MAKE_USER_FAIL = 'MAKE_USER_FAIL';
export const GET_USER_SESSION_FETCH = 'GET_USER_SESSION_FETCH';
export const GET_USER_SESSION_SUCCESS = 'GET_USER_SESSION_SUCCESS';
export const GET_USER_SESSION_FAIL = 'GET_USER_SESSION_FAIL';

// houseAction Types

export const MAKE_HOUSE_FETCH = 'MAKE_HOUSE_FETCH';
export const MAKE_HOUSE_SUCCESS = 'MAKE_HOUSE_SUCCESS';
export const MAKE_HOUSE_FAIL = 'MAKE_HOUSE_FAIL';
export const EDIT_HOUSE_INFO = 'EDIT_HOUSE_INFO';
export const SAVE_HOUSE_INFO = 'SAVE_HOUSE_INFO';
export const CANCEL_SAVE_HOUSE_INFO = 'CANCEL_SAVE_HOUSE_INFO';
export const SAVE_HOUSE_INFO_FETCH = 'SAVE_HOUSE_INFO_FETCH';
export const SAVE_HOUSE_INFO_SUCCESS = 'SAVE_HOUSE_INFO_SUCCESS';
export const SAVE_HOUSE_INFO_FAIL = 'SAVE_HOUSE_INFO_FAIL';

// playgroundAction Types

export const SET_CURRENT_COUNTER_TOP = 'SET_CURRENT_COUNTER_TOP';
export const SET_CURRENT_ROOF = 'SET_CURRENT_ROOF';
export const SET_CURRENT_SIDING = 'SET_CURRENT_SIDING';
export const SET_CURRENT_AC = 'SET_CURRENT_AC';
export const SET_CURRENT_FURNACE = 'SET_CURRENT_FURNACE';
export const SET_CURRENT_FLOORING = 'SET_CURRENT_FLOORING';
export const SET_CURRENT_ADDING_SQFT = 'SET_CURRENT_ADDING_SQFT';
export const SET_CURRENT_PAINTING = 'SET_CURRENT_PAINTING';
export const SET_CURRENT_VALUE = 'SET_CURRENT_VALUE';

// landingpageAction Types

export const GET_VALUATION_FETCH = 'GET_VALUATION_FETCH';
export const GET_VALUATION_SUCCESS = 'GET_VALUATION_SUCCESS';
export const GET_VALUATION_FAIL = 'GET_VALUATION_FAIL';

// displayAction Types

export const TOGGLE_SIDEBAR_DRAWER = 'TOGGLE_SIDEBAR_DRAWER';
export const CLOSE_SIDEBAR_DRAWER = 'CLOSE_SIDEBAR_DRAWER';
export const SET_MOBILE_UPGRADE = 'SET_MOBILE_UPGRADE';

// storageAction Types

export const IMAGE_UPLOAD_FETCH = 'IMAGE_UPLOAD_FETCH';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const IMAGE_UPLOAD_FAIL = 'IMAGE_UPLOAD_FAIL';
export const IMAGE_DOWNLOAD_FETCH = 'IMAGE_DOWNLOAD_FETCH';
export const IMAGE_DOWNLOAD_SUCCESS = 'IMAGE_DOWNLOAD_SUCCESS';
export const IMAGE_DOWNLOAD_FAIL = 'IMAGE_DOWNLOAD_FAIL';
