// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:0b1cd1b4-9317-4db9-8797-88b669850445",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_7asus0LKA",
    "aws_user_pools_web_client_id": "31de8of5dd1lshel0l9rqhosqb",
    "oauth": {
        "domain": "labs12realestatefe3debf5fd-3debf5fd-production.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://dnir3w34tjdc5nwkbxvs2uxnym.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
